name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: npm install

      # step 3
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.5.0
        with:
          server: "ftp.hillsidecollegesd.com"
          username: "austin@car.hillsidecollegesd.com"
          password: "@0}d4YT4dd,h"
          port: "21"
          protocol: "ftp"
          local-dir: "./" # Local directory to deploy
          server-dir: "/home/hillside/car.hillsidecollegesd.com"  # Target directory on server
          exclude:
        
            - "node_modules/**"  # Exclude node_modules
            - "*.yml"    # Exclude workflow files


            # edit
